spring.application.name=personapp
spring.datasource.url=jdbc:mysql://localhost:3306/demo
spring.datasource.username=root
spring.datasource.password=yearup26

# Here's how to use environment variables to set these
#spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/personapp}
#spring.datasource.username=${DB_USERNAME:root}
#spring.datasource.password=${DB_PASSWORD:yearup26}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
